version: 2.1

environment: &environment
  GRADLE_OPTS: -Dorg.gradle.daemon=false

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

jobs:
  build:
    docker:
      - image: gradle:6.5.1-jdk11
    environment: *environment
    steps:
      - checkout
      - run: gradle --build-cache assemble
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: gradle:6.5.1-jdk11
    environment: *environment
    steps:
      - attach_workspace:
          at: .
      - run: gradle check

  publish:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: export IMAGE_TAG="$(date -u +%Y%m%d%H%M%S)-sha_${CIRCLE_SHA1:0:7}"
      - aws-ecr/build-and-push-image:
          repo: docker-java-circleci
          tag: ${IMAGE_TAG}

workflows:
  build-test-publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test