version: 2

jobs:
  build:
    docker:
      - image: gradle:6.5.1-jdk11
    steps:
      - checkout
      - run: |
          gradle --build-cache assemble

  test:
    docker:
      - image: gradle:6.5.1-jdk11
    steps:
      - run: |
          gradle check

workflows:
  version: 2

  build-test-publish:
    jobs:
      - build
      - test:
          requires:
            - build